app1:
  - changed-files:
    - any-glob-to-any-file: 'app1/**'

app2:
  - changed-files:
    - any-glob-to-any-file: 'app2/**'

app3/hoge:
  - changed-files:
    - any-glob-to-any-file: 'app3/hoge/**'
