name: tagpr
on:
  push:
    branches:
      - main

jobs:
  list-changed-directories:
    runs-on: ubuntu-latest

    outputs:
      changed-directories: ${{ steps.list-changed-directories.outputs.changed-directories }}

    steps:
      - uses: actions/checkout@v6

      - uses: sankichi92/list-changed-directories@v1
        id: list-changed-directories
        with:
          target-file: .tagpr

  tagpr:
    runs-on: ubuntu-latest
    needs: list-changed-directories
    if: needs.list-changed-directories.outputs.changed-directories != '[]'
    strategy:
      matrix:
        working-directory: ${{ fromJSON(needs.list-changed-directories.outputs.changed-directories) }}
    steps:
      - uses: actions/create-github-app-token@29824e69f54612133e76f7eaac726eef6c875baf # v2.2.1
        id: app-token
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
          token: ${{ steps.app-token.outputs.token }}

      - uses: Songmu/tagpr@da82ed6743aec90049892070edd5561335904a9e # v1.17.0
        with:
          config: ${{ matrix.working-directory }}/.tagpr
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
